# Generated by Django 3.1.7 on 2021-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210221_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='userid',
            field=models.IntegerField(default=1),
        ),
    ]
