# Generated by Django 3.2 on 2021-05-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_item_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='order_ref',
        ),
    ]
